language: node_js
node_js:
- '6.9'
before_install: npm prune
before_cache: npm prune
install: npm install
script: npm start
notifications:
  slack: craft-ai:ZNnQErHJhw40oKmphy3fNGza
  email:
  - ops@craft.ai
env:
  global:
  - secure: ZWTHOoqCN0zxtT0KHfodXM4B2UrFo7/BYrUhdFJJJAf0a7JmMb68Y16kZQDg+dU7Wzr7IsE0wkg+7Ad7aXvOHyDyEA7/kc94Rnajeh8qlMoN8h5wbpb6al1rpnrTDak5feSc2mO8EYZdBaQ/ox3wOMs6gknAfv/LgSs7Y3w8PZTOtnc4DavOntVSpvfCERxwcsaZU05zZB0jPM/PiDOOV3Wc4QNLum04GdYZ1qDk4FzK7JpZo0w+3T3LqUnHyy5c8/qM76eZfmH8ormyVQdcMdHPhm8uMLEbJ0iJ8SgMmSkE7z5WGnj5Xs/OCXdDTAJbItmBSi0h+8AXQH078vu/hT/YaYFQAyyCXetM6UYttiAIDcmAg82uzzP18y1V9UtP8vBnAVXMMWLZvfD3bwbMj2cvsm5mPu5iW0EnXm1M93Ksf2R3KNzPkuQDOHWSKd5I7Xk8lxLJzaQ4SGEqd9CfVtJrixTxtuu89d78onIUlzjcDVZ5Vo864baEbowmFmjPw1V0gk95HOE+BcHpr2fDtkzTCTIEdyHTN8bi3vbJqphTaxhXxOHmvtEX22x8AFF1844FrVNK8TYFDc/kJEhGq4FQ1GGvU7EG3uaO7IdoUikHuxHQvHBpDofdeq7w2HfL70JfcvDilxxgv2TZZRblgW7YX3xDXaG6FXOT+1KWO2g=
  - secure: mI/9JPOso+MDsBZiXL/BJ0yWuAkKKOzwrladiM3VZi8Qkvkaxz+9/+jbKdP7eQDMNL+6XQLd/GAFQimeBUG7M/NzPzbq3bz09oJS/1wRtkn9jfIQQYE6nhR0YmQdUK7Wz482YHcBBtyNwVckY2QUmvDHmeR6Fy8cWqmT5kuKnYJfNKYKpoQVdo2UG0yEmAfdKYvA0ZADa7MpyOwPRCxoI5QK8I3Xhw7xY2vo7xFn8vkUM4AVu6htP1r6rmPDqc1PNzKdiVjAdUevSVU/3sN7X3qCY5xPe5L7iEmulE3MC7fLF88Bw3g7VoAs2dJ7LbNlFCr5plugoF/PIcmoXmwWhgF3YXw++8VgIjot5KuZbK/HSgiEsxuI0Nv4DJ4f5IzvTV7n/DxWghk2pa1gwpCh10vjjBTx/3/3ryNdqF7RZ4RPpCoimzqXYqmpYXTDPAZ18xcJOMs6BBNymPeNlTtPPR16CH9fejR2a4tN17V6lOBxl+g1NzleFLtGjwcjGlizZHq6UTOwpMiu2q88tKcqz1WQC81JvpyLgomYv3lHK7Vf/Ijra7Yy+sNBWdcZ+usgxjOI9Y36smICdcHhXPNoHFi+cUOx1qDhYYoKp3qmBPXryrHtArdiXUUGf6SFnqYEYXCJpbomRLwm8Bju6XiIKMgX0ysIu+s484eZVQKkQGY=
